spring:
  application.name: exammate-backend
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties.mail.smtp:
      protocol: smtp
      auth: true
      starttls.enable: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000
    protocol: smtp

server:
  servlet:
    context-path: /api/v1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs


app.allowed-origins: ${HOSTED_FRONTEND_URL}, ${LOCAL_HOST_FRONTEND_URL}

jwt:
  secret: ${JWT_SECRET:yyU0AdqdxwdENHux5OoQ8Pg9kYddnXm16fOxTPMHsqU=}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
